# Generated by Django 5.2.17 on 2026-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='max_clients',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
